from core import Sprite

WINDOW_TITLE = "Koi Koi"

CARD_TYPE_PINE_CRANE = 0
CARD_TYPE_PINE_PLAIN1 = 1
CARD_TYPE_PINE_PLAIN2 = 2
CARD_TYPE_PINE_RED_POEM_TANZAKU = 3
CARD_RECT_COLOR = (195, 177, 225)
CARD_RECT_WIDTH = 64 * 2
CARD_RECT_HEIGHT = 108 * 2
CARD_SPRITE_WIDTH = 64 * 2
CARD_SPRITE_HEIGHT = 108 * 2

JANUARY = 1
FEBRUARY = 2
MARCH = 3
APRIL = 4
MAY = 5
JUNE = 6
JULY = 7
AUGUST = 8
SEPTEMBER = 9
OCTOBER = 10
NOVEMBER = 11
DECEMBER = 12

CARD_SLOT_RECT_WIDTH = CARD_RECT_WIDTH
CARD_SLOT_RECT_HEIGHT = CARD_RECT_HEIGHT
CARD_SLOT_RECT_COLOR = (164, 0, 32)
CARD_SLOT_X_OFFSET = 16
CARD_SLOT_Y_OFFSET = 16

CARD_TABLE_RECT_WIDTH = CARD_SLOT_RECT_WIDTH * 5 + CARD_SLOT_X_OFFSET * 4
CARD_TABLE_RECT_HEIGHT = CARD_SLOT_RECT_HEIGHT * 2 + CARD_SLOT_Y_OFFSET
CARD_TABLE_RECT_COLOR = (8, 164, 32)

CARD_HAND_RECT_WIDTH = CARD_SLOT_RECT_WIDTH * 8 + CARD_SLOT_X_OFFSET * 7
CARD_HAND_RECT_HEIGHT = CARD_RECT_HEIGHT
CARD_HAND_RECT_COLOR = (70, 50, 212)

CARD_BACK_RECT_WIDTH = CARD_RECT_WIDTH
CARD_BACK_RECT_HEIGHT = CARD_RECT_HEIGHT
CARD_BACK_SPRITE_WIDTH = CARD_SPRITE_WIDTH
CARD_BACK_SPRITE_HEIGHT = CARD_SPRITE_HEIGHT
CARD_BACK_SPRITE = Sprite.load("textures/card_back.png", CARD_BACK_SPRITE_WIDTH, CARD_BACK_SPRITE_HEIGHT)

CARD_PINE_CRANE_RECT_WIDTH = CARD_RECT_WIDTH
CARD_PINE_CRANE_RECT_HEIGHT = CARD_RECT_HEIGHT
CARD_PINE_CRANE_SPRITE_WIDTH = CARD_SPRITE_WIDTH
CARD_PINE_CRANE_SPRITE_HEIGHT = CARD_SPRITE_HEIGHT
CARD_PINE_CRANE_SPRITE = Sprite.load("textures/pine_crane.png", CARD_PINE_CRANE_SPRITE_WIDTH, CARD_PINE_CRANE_SPRITE_HEIGHT)
CARD_PINE_CRANE_SEASON = JANUARY

CARD_PINE_PLAIN1_RECT_WIDTH = CARD_RECT_WIDTH
CARD_PINE_PLAIN1_RECT_HEIGHT = CARD_RECT_HEIGHT
CARD_PINE_PLAIN1_SPRITE_WIDTH = CARD_SPRITE_WIDTH
CARD_PINE_PLAIN1_SPRITE_HEIGHT = CARD_SPRITE_HEIGHT
CARD_PINE_PLAIN1_SPRITE = Sprite.load("textures/pine_plain1.png", CARD_PINE_PLAIN1_SPRITE_WIDTH, CARD_PINE_PLAIN1_SPRITE_HEIGHT)
CARD_PINE_PLAIN1_SEASON = JANUARY

CARD_PINE_PLAIN2_RECT_WIDTH = CARD_RECT_WIDTH
CARD_PINE_PLAIN2_RECT_HEIGHT = CARD_RECT_HEIGHT
CARD_PINE_PLAIN2_SPRITE_WIDTH = CARD_SPRITE_WIDTH
CARD_PINE_PLAIN2_SPRITE_HEIGHT = CARD_SPRITE_HEIGHT
CARD_PINE_PLAIN2_SPRITE = Sprite.load("textures/pine_plain2.png", CARD_PINE_PLAIN2_SPRITE_WIDTH, CARD_PINE_PLAIN2_SPRITE_HEIGHT)
CARD_PINE_PLAIN2_SEASON = JANUARY

CARD_PINE_RED_POEM_TANZAKU_RECT_WIDTH = CARD_RECT_WIDTH
CARD_PINE_RED_POEM_TANZAKU_RECT_HEIGHT = CARD_RECT_HEIGHT
CARD_PINE_RED_POEM_TANZAKU_SPRITE_WIDTH = CARD_SPRITE_WIDTH
CARD_PINE_RED_POEM_TANZAKU_SPRITE_HEIGHT = CARD_SPRITE_HEIGHT
CARD_PINE_RED_POEM_TANZAKU_SPRITE = Sprite.load("textures/pine_red_poem_tanzaku.png", CARD_PINE_RED_POEM_TANZAKU_SPRITE_WIDTH, CARD_PINE_RED_POEM_TANZAKU_SPRITE_HEIGHT)
CARD_PINE_RED_POEM_TANZAKU_SEASON = JANUARY

DEBUG_SHOW_RECTS = True